### ISSUE TITLE
Write gridding-up of simulated data

### ISSUE THREAD

**Issue by cknaut** [phys201/optical_lattice#1]
For each lattice site, add P*P grid as pixels and sum over them.

![image](https://user-images.githubusercontent.com/4958226/79289811-571f0180-7e98-11ea-9223-813b70415e30.png)

Implement in `output_pixelated_counts` in `GeneratedLatticeImage`.

**Comment by eknall** [comment]
![image](https://user-images.githubusercontent.com/51799857/79979169-14988e80-846f-11ea-9626-003a3f11e589.png)
generated data now mimicks CCD data with and optical_lattice region and only integer coordinate positions possible (like pixels)
zoom of optical lattice region is shown above, full generated CCD output with significant background counts shown below. Note there are different grids shown in each graphic.
![image](https://user-images.githubusercontent.com/51799857/79979556-b1f3c280-846f-11ea-9a80-80c998004d4d.png)
