### ISSUE TITLE
Consider simulating an entire image

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#10]
Currently your generative model operates on a single-site basis, rather than simulating the entire image composed of all sites. This is problematic because as you move to a tighter lattice spacing, you may have photons from one atom stray into the next lattice site.

You should be able to simulate the entire image at once by using a q_i variable for each lattice site that determines whether it is full or empty (similar to the mixture model in assignment 9 where each data point could be part of either distribution).

**Comment by sfozturk61** [comment]
With the new mixture model, we analyze the image once without operating site by site. Each site has boolean q value. tt.linalg.kron takes q's and the PSF as inputs and formes a grid. 

single_atom = Aa * np.exp(-(X**2 + Y**2) / (2 * std**2)) #Gaussian PSF
atom = tt.slinalg.kron(q, single_atom) #gridding based on q's
good_data = pm.Normal.dist(mu=atom, sd=sigma_a).logp(data_2D) #likelihood for the counts from atoms
