### ISSUE TITLE
tutorial notebook shouldn't be in package

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#13]
The tutorial notebook should be in the root of the repository, not inside the package architecture. I know it can be a bit confusing, but here's a summary. The GitHub repository can hold any number of things, such as a license file, a .gitignore file, some continuous integration files, etc. One of the things in the repository is your python package. This is a set of python files and associated test data that can be packaged by setup.py into a package for others to install and use. The tutorial notebook doesn't fit into the package - it can't (and shouldn't) be accessible by `import optical_lattice` so it belongs in the repository root.

**Comment by sfozturk61** [comment]
The tutorial notebook is moved to the root directory.

**Comment by barkls** [comment]
Unfortunately this change broke all the imports in the tutorial notebook. I recommend bringing everything into the `optical_lattice` namespace by importing them in `__init__.py`. That way the tutorial notebook could `from optical_lattice import GeneratedLatticeImage` for example.
