### ISSUE TITLE
More explanation of parameters in tutorial notebook would be useful

### ISSUE THREAD

**Issue by Bettyxhu** [phys201/optical_lattice#18]
I'm not very familiar with your field, so perhaps this isn't actually a problem. But I think the "analysis parameters" in your tutorial notebook could use more explanation--for example, should threshold_buffer, shift_up, shift_left be numbers you should know when you're doing the experiment? Or are these actually just initial guesses for the function?

**Comment by eknall** [comment]
This particular confusion is only related to the deconvolution model which exists only for completeness and to show the historical approach to optical lattice imaging. Still it is good to be clear. So, we added some clarification.
