### ISSUE TITLE
Some misunderstandings I had

### ISSUE THREAD

**Issue by cfpark00** [phys201/optical_lattice#24]
Is the expectation of the number of background photon count equal to N_backg*lam_backg?

I am confused on the motivation of background photon generation.
From the code, I think is it performing N_backg draws from a Poisson distribution of lambda=lam_backg. And then it places this amount of photon counts randomly in the grid.

Why is this physically more motivated than just sampling a number from a Poisson distribution of lambda= N_backg*lam_backg?

Furthermore, I think this is actually mathematically equivalent:
https://llc.stat.purdue.edu/2014/41600/notes/prob1805.pdf
Although I didn't check the proof here myself.

Thank you in advance,

-Core

**Comment by sfozturk61** [comment]
This is a good question. N_backg is the number of samples drawn from a Poisson distribution with an expected number lam_back. 

dark_count = np.random.poisson(lam_backg, N_backg) #create dark counts sampling from a Poisson distribution, this gives numbers corresponding to number of dark counts

Therefore np.sum(dark count) is the total number of background photons. Then these many background photons are uniformly placed on the camera with:

dark_count_location_x = np.random.choice(CCD_x, np.sum(dark_count), replace=True) #pick a random, uniform x location for the dark counts

where CCD_x is just the pixelated locations: CCD_x = np.arange(0, CCD_resolution, 1) #x-pixel locations

So I think the attached proof does not apply to our case. We do not add Poisson processes. We sample from a Poisson process with an expected value, find the total counts and place those counts (spatially) uniformly on the image.

Thanks for the question!
