### ISSUE TITLE
nose not running any tests

### ISSUE THREAD

**Issue by HelenaCasademunt** [phys201/optical_lattice#26]
Even though you have some tests in the tests folder, when I use nosetests to run the tests, I get a message that says it ran 0 tests. Not sure why this is happening or if you're using a different method to run the tests, but it might be worth checking.

**Comment by cknaut** [comment]
Can you please check that you run `nosetests` from the right directory? The `nosetests` command must be run from the `optical_lattice` subdirectory. For us, i works fine locally and our github workflow which executes `nosetests` remotely also doesn't throw an error. Let me know if the error persists and I'll reopen this issue.
