### ISSUE TITLE
Some methods are not used

### ISSUE THREAD

**Issue by HelenaCasademunt** [phys201/optical_lattice#29]
In LatticeImageAnalyzer, sample_mixture_model() and setup_mixture_model() are not used. It would be useful for a potential user to see an example using all the methods. If they're not meant for the user to run, consider making them private.

**Comment by eknall** [comment]
Extraneous methods have been removed in recent commits. See for example 693f95388afeeac0d15fd1478470d93d4f01844a "Nex Mixture Model Added"
