### ISSUE TITLE
Reopening Poisson Sampling Issue

### ISSUE THREAD

**Issue by cfpark00** [phys201/optical_lattice#32]
This is a follow up to #24 .

I do not understand this part:
"So I think the attached proof does not apply to our case. We do not add Poisson processes."
it seems to me that adding up the result of N_backg samplings from a Poisson distribution of lambda=lambda_backg is precisely adding Poisson processes. (It wouldn't work if it was np.prod(dark count))

After a few ctrl-F, I assume that dark_count is only used in the form of np.sum(dark count). Is this right?

Furthermore, I am saying that this is independent of any use of np.sum(dark count).

The following code will test this:
```
import numpy as np
import matplotlib.pyplot as plt
a=3 # corresponding to N_backg
b=25 # corresponding to lam_backg
c1sums=[]
c2s=[]
for i in range(100000):
    c1=np.random.poisson(b,a)
    c1sums.append(np.sum(c1))
    c2=np.random.poisson(b*a)
    c2s.append(c2)
_=plt.hist(c1sums,alpha=0.5,bins=101)
_=plt.hist(c2s,alpha=0.5,bins=101)
```

It seems that c2 has the same pdf as np.sum(c1)

Tell me if I am still confused, I will tag @barkls for some help.

Thank you,

Core

P.S: I think this has very minimal effects on the running speed, but I am curious why it is motivated to model the background as a sum of Poisson rather than one big Poisson.

**Comment by cfpark00** [comment]
Please tell me if I'm confusing something :)

**Comment by sfozturk61** [comment]
Hey Core! 

- That's right dark_count is used in the form of sum.

- After reviewing the code and the mathematical proof that you sent, I realized that you touched a very critical point. I agree with what you are saying, in fact, the proof applied to our case is as follows:

We generate N random Poisson variables with expected values \lambda and add them together. From the proof, we know that the sum of the Poisson random variables X_1, X_2, ... X_N with each having \lambda is also a Poisson random variable Z = \sum X_i with \lambda_N = \sum \lambda = N \lambda. This is exactly what we have: N * \lambda.

I guess this is what you were mentioning and this what your code numerically shows. In fact, generating from a single Poisson with an expected value N * \lambda is 10 times faster. So we will just switch to that.

I am glad that you mentioned this, thanks a lot!

**Comment by sfozturk61** [comment]
With that, I changed the code to:

dark_count=np.random.poisson(N_back*lam_back)   #sample from a 'Big Poisson' with  expected value N * \lam

dark_count_location_x = np.random.choice(CCD_x, dark_count, replace=True) #randomly and uniformly place as many counts as dark_count on the CCD

This way we reduced the number of parameters from two to one - only the multiplication matters - and got rid of summation and most importantly sampling many times from the Poisson distribution.

**Comment by cfpark00** [comment]
Great, thank you.

-Core

**Comment by barkls** [comment]
Your functions and tutorial explanation should be updated to reflect this change that there's now only one parameter needed to describe the background magnitude

**Comment by sfozturk61** [comment]
The code is updated to have the only one parameter lam_back which was lam_back * N_backg.
