### ISSUE TITLE
tutorial inference doesn't work as expected

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#35]
My runs of the tutorial notebook returned all q=0.

**Comment by cknaut** [comment]
This is weird. I reinstalled the package in an empty virtual environment and run the example getting the expected solutions. Maybe you can do the same and if the error persists we need to investigate further.

**Comment by barkls** [comment]
No, things are working now - I must have just gotten unlucky before. It's important to keep in mind that MCMC is a stochastic process. You want to make sure your tutorial example is robust enough to work every time.
