### ISSUE TITLE
comment switches in lattice generation

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#36]
The file `lattice_generation.py` includes the following code:

```python
            # Uncomment for non-inverted y
            # actual_lattice[y,x] = 1

            # Uncomment for inverted y
            actual_lattice[N-y-1, x] = 1
```

This is problematic because it's difficult to access and can't be changed at all once the package is installed. If both versions need to be run some of the time, there should be a way to specify this as input to the function.

**Comment by cknaut** [comment]
Fixed in 12d28cb1aa4aa8746a0f87d73a9636f347b7a0ac.
