### ISSUE TITLE
No way for atoms to leak fluorescence into adjacent lattice sites

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#40]
Right now, the emission for a single atom at a single lattice site is calculated, and then this emission is tiled over the grid sites containing atoms. This is fine for atoms with point spread functions much smaller than the grid spacing, but work for cases where the emission from atoms overlaps spatially. You could allow this leakage by calculating and summing the fluorescence contribution of each atom on the full image rather than just in its lattice site.

**Comment by eknall** [comment]
Closing, see commit 14476b1ec1c7227696ae27632bee06c5819856ae
