### ISSUE TITLE
setup.py dependencies

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#41]
The package and tutorial notebook use some packages that aren't specified as dependencies in setup.py - seaborn, scipy, theano. Additionally, scikit-image is specified but not used in the package (as far as I can tell)

**Comment by cknaut** [comment]
We probably rely on `searborn` `scipy` and `theano` being installed as dependency for some other package (I suspect `pymc3` and `pandas`). Is it bad practice to rely on this third party dependency specification? `scikit-image` is used in the `deconvolution_analysis` module.

**Comment by barkls** [comment]
Yes, since those other packages may change their dependencies. Since you
are calling things from those packages, it's up to you to make sure they
are installed for all users.
