### ISSUE TITLE
tutorial requires more explanation

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#6]
The tutorial notebook should include an explanation of the model being used to analyse the data.

**Comment by sfozturk61** [comment]
To analyze the generated data and find the probability of occupation by an atom for each lattice site a generative mixture model is used on `pymc3`. The log-likelihood for that model is defined as:

$$ \log(L) = q \log{N(\mu_a, \sigma_a)} + (1-q)\log{N(\mu_b, \sigma_b)} $$

where $N(\mu_a, \sigma_a)$ and $N(\mu_b, \sigma_b)$ are the generative models for the atoms and the background (spurious photons) respectively. Here $\mu_a$ and $\mu_b$ are given as:

$$ \mu_a = A_a \exp\left(-\frac{(x-x_c)^2 + (y-y_c)^2}{2\sigma^2}\right) $$
$$ \mu_b = A_b U((x_0,x_1),(y_0,y_1)) $$

where the point spread function for the atoms, $\mu_a$ is modelled as 2D Gaussian centered at $x_c,y_c$ with a width and amplitude of $\sigma$ and $A_a$ and the background $\mu_b$ is modelled as a uniform distribution in a given range with the amplitude $A_b$. Finally the generative models have a Gaussian uncertainty of $\sigma_a$ and $\sigma_b$ for the atoms and the background respectively.

The model analyzes a 2D image of photon counts for the whole lattice. It uses a prior probability $P$ corresponding to the occupation probability of the whole lattice to generate an array of Boolean numbers, $q$. Those $q$ numbers are drawn from a Bernouilli distribution with the probability $P$ and the number $q_{ij}$ is 1 if the lattice site $ij$ is occuiped and 0 if not. Then, the model places an array of Gaussians with an amplitude $A_a$ to lattice sites $ij$ for $q_{ij}=1$. Likewise the model places an array of uniform distributions with an amplitude $A_b$ to lattice sites $ij$ for $q_{ij}=0$. The amplitude are also assigned as model parameters with uniform prior probabilities. Finally, the log-likelihood is modelled by adding those two arrays for the atoms and the background. 

The samples are drawn from this log-likelihood and posterior probability is marginalized over all parameters but $q$'s which correspond to the occupation numbers for the lattice sites.
