### ISSUE TITLE
Extra files in package

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#7]
There are lots of files in the repository that don't seem to belong. There should only be one jupyter notebook, tutorial.ipynb. There shouldn't be any python files that are not used (e.g. lattice_image.py). There should only be enough data for your tutorial notebook and tests to run.

**Comment by sfozturk61** [comment]
Extra files are moved into the Scratch Files folder.

**Comment by barkls** [comment]
There shouldn't be a Scratch Files folder.

Since git is meant to track changes to files over time,  anyone who downloads a repository isn't just downloading its current state, but all the information necessary to recreate it any state in the past. This means it's important to limit the files included in a repository to those that are strictly necessary.

You can keep a Scratch folder on your computer, but you shouldn't commit those files to github. You can even add the folder to your .gitignore so that git won't keep track of it at all.

**Comment by sfozturk61** [comment]
All extra files are deleted.
