### ISSUE TITLE
long functions

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#8]
Right now your code performs most operations in large functions that go through multiple steps. This makes it difficult to modify your code for the future and impossible to test thoroughly. Try breaking code up into bite-size chunks that each perform a single operation.

**Comment by sfozturk61** [comment]
Deconvolution analysis is divided into short functions that performs each step separately. A master function is added at the end that runs those functions in the right sequence.

**Comment by eknall** [comment]
recent commits resolved this issue. Updated model no longer visits site by site. see eg. 693f95388afeeac0d15fd1478470d93d4f01844a
