### ISSUE TITLE
analysis code is inefficient

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#9]
The code in `lattice_analyser.py` is not very efficient. That's not a huge problem now, but it will cause long runtimes as you try to analyse larger datasets and increase the complexity of your model.

It looks like the main goal of this code is to figure out which x & y coordinates belong in which grid spaces. You should be able to do this with numpy ufuncs to avoid both nested for loops and arbitrary placeholder values.

**Comment by sfozturk61** [comment]
For loops are replaced with ufuncs everywhere. And the analysis is done over the whole image only once instead of looping over each site.
